# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    ensure_git_status_clean
  end

  desc "Unit testing lane"
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
    scan(device: "iPhone SE (11.2)")
  end
end
